### ISSUE TITLE
core declaration code

### ISSUE THREAD

**Issue by ghost** [ReactorSwift/Reactor#12]
Well, it's not an issue as such, but a question about the **_core_** for Reactor.

I have looked at the example code on the GitHub repo and those are useful, thanks.
The only thing I couldn't see was an example of how and where to declare the **_core_**.

The example of `var core = App.sharedCore` seems to assume that the **_sharedCore_**
has already been declared, but doesn't show the syntax of how to do so.

An example of how to declare the _**core**_ will be very useful. Thanks.

**Comment by jarsen** [comment]
Good call! That would be good to include somewhere in the documentation.

In the mean time, here's how I do it personally:

```swift
enum App {
    static let sharedCore = Core(state: AppState(), middlewares: [
        ReachabilityMiddleware(),
        ErrorLogger(),
        AnalyticsMiddleware(),
        // etc..
        ])
}
```

**Comment by ghost** [comment]
Thanks for that. I'll close this, as I am implementing ReSwift instead.
