### ISSUE TITLE
Making Reactor a organisation

### ISSUE THREAD

**Issue by thomaspaulmann** [ReactorSwift/Reactor#7]
How about moving `Reactor` to an organisation? It would be easier to set up separate repositories for the design, the framework itself and a couple of examples.
I would be more than happy to help.

**Comment by thomaspaulmann** [comment]
How about [reactor-swift](https://github.com/reactor-swift) as organisation name? I've presaved it ;-)

**Comment by jarsen** [comment]
I think that sounds like a good idea. If we move the repo, what's the experience like for people who have already starred the repo? Is it possible to set it up to forward them? Never done this before.

**Comment by thomaspaulmann** [comment]
[https://help.github.com/articles/about-repository-transfers/](About respository transfers): "When you transfer a repository, its issues, wiki, stars, and watchers are also transferred" 

Should be ok to transfer ✌️

**Comment by jarsen** [comment]
Awesome. Thanks for finding this. Let me mull it over a little bit.

**Comment by jarsen** [comment]
Alright. Transfer's gone through. I'm wondering though about the organization name as `reactor-swift`. would `ReactorSwift` would be better? Unsold either way. Just wondering if hyphens are more unsightly in a Cartfile. Anyway, if we want to rename the org, now would be the time.

**Comment by thomaspaulmann** [comment]
You're right. Seems more natural with ReactorSwift. I will rename it!
